stages:
  train:
    cmd: python src/transnormer/models/train_model.py
    deps:
    - data/interim/
    - src/transnormer/data/loader.py
    - src/transnormer/preprocess/translit.py
    - src/transnormer/models/train_model.py
    params:
    - training_config.toml:
      - data
      - tokenizer
      - language_models
      - training_hyperparams
      - beam_search_decoding
    outs:
    - models/model/
